# Generated by Django 5.1 on 2024-11-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='projuct_image',
            new_name='product_image',
        ),
    ]
