# Generated by Django 5.1 on 2024-11-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_location_customer_address_customer_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='locality',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
    ]
